# config/moonshine.yml is loaded both by capistrano and moonshine.
#  The result is the values defined here can be used in `config/deploy.rb` directly
#  and in `app/manifest/application_manifest.rb` via `configuration`

# ruby to install at `cap deploy:setup` time. If you change this value, you
# need to run `cap ruby:upgrade`. Currently allowed values include: mri,
# src187, ree, ree187
:ruby: ree187
:application: nucmic
:user: rails
:deploy_to: /var/www/apps/nucmic
:domain: get-nucleus.com
:domain_aliases:
  - www.get-nucleus.com
  - micro.get-nucleus.com

:repository: git@github.com:electricgraffitti/nucmic.git
:branch: no-video

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
 - attachments

# Use :shared_config to copy directories straight from your local project
# directory to the server: these are files that you don't have/want in scm.
:shared_config:
 - config/database.yml
 - config/app_config.yml

# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config

# Specify native dependencies of gems. Moonshine comes with some preconfigured
# defaults, but this allows you to add to them. Please file an issue at
# http://github.com/railsmachine/moonshine/issues if there are additional gem
# dependencies Moonshine should know about.
:rubygems:
  :sources:
    - http://gemcutter.org
    - http://gems.rubyforge.org
    - http://gems.github.com

# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :max_pool_size: 3
  :use_global_queue: true
  :version: 2.2.15
:mysql:
  :innodb_buffer_pool_size: 128M
